#include <R_ext/RS.h>

void F77_SUB(loglik)( double * Y0, 
		      double * X0,
		      int * idg0,
		      int * ny0,
		      int * ns0,
		      int * nv0,
		      int * nobs0,
		      int * nmes0,
		      int * npm0,
		      double * b0,
		      int * nfix0,
		      double * bfix0,
		      double * zitr0,
		      int * fix0,
		      int * methInteg0,
		      int * nMC0,
		      int * dimMC0,
		      double * seqMC0,
		      double * loglik);

void F77_SUB(dens)( double * re0,
		    double * best0,
		    double * Y0, 
		    double * X0,
		    int * idg0,
		    int * ny0,
		    int * ns0,
		    int * nv0,
		    int * nobs0,
		    int * nmes0,
		    int * npm0,
	 	    int * nea0,
		    double * zitr0,
		    int * ind0,
		    int * nmescur0,
		    double * dens);
